### ISSUE TITLE
Review "observation" schema

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#111]
_Issue [RAD-52](https://jira.stsci.edu/browse/RAD-52) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Review attributes in the "observation" schema to understand their meaning and use and decide if all are needed. Write better descriptions.

**Comment by ddavis-stsci** [comment]
At the DMS-INS reference file meeting it was decided to remove the times from the observation schema. There seems to be no use case for these times and it is unclear how these times would be populated. 
Create a PR to remove these times.
