### ISSUE TITLE
Create a "ref_file" schema

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#113]
_Issue [RAD-53](https://jira.stsci.edu/browse/RAD-53) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Create a ref_file schema to document the reference files used in processing.

For reference the jwst schema is 

<https://github.com/spacetelescope/jwst/blob/master/jwst/datamodels/schemas/core.schema.yaml#L1662>

**Comment by ddavis-stsci** [comment]
I think this is done with ref_file-1.0.0.yaml:4:id: asdf://stsci.edu/datamodels/roman/schemas/ref_file-1.0.0
so I'm closing this issue.
