### ISSUE TITLE
gw_start_time & gw_end_time duplicated

### ISSUE THREAD

**Issue by ddavis-stsci** [spacetelescope/rad#144]
The gw_start_time and gw_end_time are in the guidewindow and guidestar schemas. This information should only be in the guidewindow schema. 

In addition the gw_function_start_time and gw_function_end_time should be moved from the guidestar schema and be in the guidewindow schema? What about gw_acq_exec_stat?

These should be done after the 22Q3_B6 release.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-69](https://jira.stsci.edu/browse/RAD-69)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-69?focusedCommentId=598775#comment-598775):_

I removed duplicate gw time entries, and I moved all of gw_function_start_time, gw_function_end_time, and gw_acq_exec_stat from GuideStar to GuideWindow. 

This is implemented in RAD PR-154: #154

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-69?focusedCommentId=598815#comment-598815):_

It's unclear to me what the definitions of these attributes are. We should figure this out and populate longer "description" fields but that's for a different PR.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-69?focusedCommentId=599078#comment-599078):_

I’d also move gw_fgs_mode to the gw file since it is a property of the detector. Also it appears the it uses nvarchar(10) and the longest string in guidewindow_modes-1.0.0 is 18 characters long.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-69?focusedCommentId=599674#comment-599674):_

PR Approved and closed.
