### ISSUE TITLE
Change W146 to F146

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#148]
_Issue [RAD-67](https://jira.stsci.edu/browse/RAD-67) was created on JIRA by [Tyler Desjardins](https://jira.stsci.edu/secure/ViewProfile.jspa?name=desjard):_

In the list of optical elements ([https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/wfi_optical_element-1.0.0.yaml)] , the filter W146 should be changed to F146. Gisella confirmed this with the project that the official name of the filter will be F146 moving forward.

This shouldn't affect any of the current test science or reference files, but CRDS may need to be updated as well for when it checks optical element names.

**Comment by ddavis-stsci** [comment]
Fixed in #156 (closing).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-67?focusedCommentId=598704#comment-598704):_

[Tyler Desjardins](https://jira.stsci.edu/secure/ViewProfile.jspa?name=desjard) Is this approved by MO?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Tyler Desjardins](https://jira.stsci.edu/secure/ViewProfile.jspa?name=desjard) on [JIRA](https://jira.stsci.edu/browse/RAD-67?focusedCommentId=598884#comment-598884):_

This is approved. Consulted [Christina Gallo](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cgallo) who checked with [Ariel Bowers](https://jira.stsci.edu/secure/ViewProfile.jspa?name=abowers). I followed up with Josh Schlieder in the PSO, who confirmed the name change, and said GSFC will start updating their webpages etc. soon.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-67?focusedCommentId=599307#comment-599307):_

#156

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-67?focusedCommentId=599311#comment-599311):_

This was implemented in RAD PR-156: #156
