### ISSUE TITLE
Investigate Validation Enforcement of Units

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#169]
_Issue [RAD-76](https://jira.stsci.edu/browse/RAD-76) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Investigate the feasibility and amount of work needed to add unit checking of quantities within the validation routine.

**Comment by ddavis-stsci** [comment]
closing since Jira issue is resolved.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-76?focusedCommentId=632398#comment-632398):_

This work is done and the code merged so I'm closing this issue. See RCAL-438 & RCAL-439

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-76?focusedCommentId=632398#comment-632398):_

This work is done and the code merged so I'm closing this issue. See RCAL-438 & RCAL-439

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-76?focusedCommentId=632398#comment-632398):_

This work is done and the code merged so I'm closing this issue. See RCAL-438 & RCAL-439

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-76?focusedCommentId=632398#comment-632398):_

This work is done and the code merged so I'm closing this issue. See RCAL-438 & RCAL-439

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-76?focusedCommentId=632398#comment-632398):_

This work is done and the code merged so I'm closing this issue. See RCAL-438 & RCAL-439
