### ISSUE TITLE
Delete source_type_apt from target-1.0.0.yaml

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#179]
_Issue [RAD-98](https://jira.stsci.edu/browse/RAD-98) was created on JIRA by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller):_

This attribute should be deleted:
  source_type_apt:
    title: Source type from APT (point/extended)
    type: string
    enum: [EXTENDED, POINT, UNKNOWN]
    sdf:
      special_processing: VALUE_REQUIRED
      source:
        origin: PSS:target.extended
        function: convert_extended
    archive_catalog:
      datatype: nvarchar(8)
      destination: [ScienceCommon.source_type_apt]

 <https://innerspace.stsci.edu/display/RPSS/2022-04-14+RPSDB+Splinter%3A+Defining+the+DMS+Views> discussion 
....
For JWST, the extended column is used by DMS to choose which pipeline to process data. But DMS won't do this for Roman
No need for the extended column

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625567#comment-625567):_

This is implemented in RAD PR-206: #206

**Comment by ddavis-stsci** [comment]
closing since Jira issue is resolved.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625567#comment-625567):_

This is implemented in RAD PR-206: #206

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625567#comment-625567):_

This is implemented in RAD PR-206: #206

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625567#comment-625567):_

This is implemented in RAD PR-206: #206

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625567#comment-625567):_

This is implemented in RAD PR-206: #206

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625567#comment-625567):_

This is implemented in RAD PR-206: #206

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625567#comment-625567):_

This is implemented in RAD PR-206: #206

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-98?focusedCommentId=625776#comment-625776):_

PR approved and merged.
