### ISSUE TITLE
Change SDF "origin" in ephemeris-1.0.0.yaml to use definitve/predicted ephemeris

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#188]
_Issue [RAD-97](https://jira.stsci.edu/browse/RAD-97) was created on JIRA by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller):_

JWST uses delivered definitive/predicted ephemeris values stored in METRICS_DB to populate ephemeris FITS keywords in core.ephemeris.schema.json:
        "fits_keyword" : "REFFRAME", Ephemeris ref frame (EME200) – EME2000
        "fits_keyword" : "EPH_TYPE", Definitive or Predicted
        "fits_keyword" : "EPH_TIME", MJD time of position and vel.
        "fits_keyword" : "JWST_X", barycentric JWST X coordinate at MJD_AVG
        "fits_keyword" : "JWST_Y",
        "fits_keyword" : "JWST_Z",
        "fits_keyword" : "OBSGEO-X", x spatial coordinate relative to geocentric terrestrial ref frame in meters
        "fits_keyword" : "OBSGEO-Y", y
        "fits_keyword" : "OBSGEO-Z", z
        "fits_keyword" : "JWST_DX", barycentric x componente of JWST velocitry vector
        "fits_keyword" : "JWST_DY",
        "fits_keyword" : "JWST_DZ",
        "fits_keyword" : "OBSGEODX", x component of JWST velocity vector relative to geocentric terrestrial ref frame in meters/secs
        "fits_keyword" : "OBSGEODY",
        "fits_keyword" : "OBSGEODZ",

Currently RAD ephemeris-1.0.0.yaml uses PSS database values to populate (shown below).  The SDF origin of these items.  SDF should get values from Definitive/Predicted Ephemeris products.

    title: UTC time of position and velocity vectors in ephemeris (MJD)
    type: number
    sdf:
      special_processing: VALUE_REQUIRED
      source:
        origin: PSS:ephemeris_state.ingest_time
 
  spatial_x:
    title: "[km] X spatial coordinate of Roman"
    type: number
    sdf:
      special_processing: VALUE_REQUIRED
      source:
        origin: PSS:sts_ephemeris_state.x
--
  spatial_y:
    title: "[km] Y spatial coordinate of Roman"
    type: number
    sdf:
      special_processing: VALUE_REQUIRED
      source:
        origin: PSS:sts_ephemeris_state.y
--
  spatial_z:
    title: "[km] Z spatial coordinate of Roman"
    type: number
    sdf:
      special_processing: VALUE_REQUIRED
      source:
:        origin: PSS:sts_ephemeris_state.z
--
  velocity_x:
    title: "[km/s] X component of Roman velocity"
    type: number
    sdf:
      special_processing: VALUE_REQUIRED
      source:
        origin: PSS:sts_ephemeris_state.dx
--
  velocity_y:
    title: "[km/s] Y component of Roman velocity"
    type: number
    sdf:
      special_processing: VALUE_REQUIRED
      source:

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625581#comment-625581):_

For all attribute entries above change:

origin: PSS:ephemeris_state.ingest_time

origin : Roman Science Data Processing (RSDP)

 

In the future RSDP will populate attribute values using row with closest time to exposure's mid time in DefEphemeris or PredictEphemeris table in METRICS_DB. <https://jira.stsci.edu/browse/RSDP-250>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625587#comment-625587):_

This is implemented in RAD PR-207: #207

**Comment by ddavis-stsci** [comment]
closing since Jira issue is resolved.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625581#comment-625581):_

For all attribute entries above change:

origin: PSS:ephemeris_state.ingest_time

origin : Roman Science Data Processing (RSDP)

 

In the future RSDP will populate attribute values using row with closest time to exposure's mid time in DefEphemeris or PredictEphemeris table in METRICS_DB. <https://jira.stsci.edu/browse/RSDP-250>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625587#comment-625587):_

This is implemented in RAD PR-207: #207

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625775#comment-625775):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625581#comment-625581):_

For all attribute entries above change:

origin: PSS:ephemeris_state.ingest_time

origin : Roman Science Data Processing (RSDP)

 

In the future RSDP will populate attribute values using row with closest time to exposure's mid time in DefEphemeris or PredictEphemeris table in METRICS_DB. <https://jira.stsci.edu/browse/RSDP-250>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625587#comment-625587):_

This is implemented in RAD PR-207: #207

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625775#comment-625775):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625581#comment-625581):_

For all attribute entries above change:

origin: PSS:ephemeris_state.ingest_time

origin : Roman Science Data Processing (RSDP)

 

In the future RSDP will populate attribute values using row with closest time to exposure's mid time in DefEphemeris or PredictEphemeris table in METRICS_DB. <https://jira.stsci.edu/browse/RSDP-250>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625587#comment-625587):_

This is implemented in RAD PR-207: #207

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625581#comment-625581):_

For all attribute entries above change:

origin: PSS:ephemeris_state.ingest_time

origin : Roman Science Data Processing (RSDP)

 

In the future RSDP will populate attribute values using row with closest time to exposure's mid time in DefEphemeris or PredictEphemeris table in METRICS_DB. <https://jira.stsci.edu/browse/RSDP-250>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625587#comment-625587):_

This is implemented in RAD PR-207: #207

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625775#comment-625775):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625775#comment-625775):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625775#comment-625775):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625587#comment-625587):_

This is implemented in RAD PR-207: #207

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625587#comment-625587):_

This is implemented in RAD PR-207: #207

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-97?focusedCommentId=625775#comment-625775):_

PR approved and merged.
