### ISSUE TITLE
Create ModelContainer Schema

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#191]
_Issue [RAD-72](https://jira.stsci.edu/browse/RAD-72) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Create the schema for the level 3 container of models that associations will be used to populate.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606087#comment-606087):_

This is on hold until we define the work better.

**Comment by ddavis-stsci** [comment]
closing since Jira issue is resolved

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606087#comment-606087):_

This is on hold until we define the work better.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606087#comment-606087):_

This is on hold until we define the work better.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=625975#comment-625975):_

Closing this ticket as [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) does nto need the schema for his RDM implementation.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606087#comment-606087):_

This is on hold until we define the work better.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=625975#comment-625975):_

Closing this ticket as [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) does nto need the schema for his RDM implementation.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606087#comment-606087):_

This is on hold until we define the work better.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606087#comment-606087):_

This is on hold until we define the work better.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=625975#comment-625975):_

Closing this ticket as [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) does nto need the schema for his RDM implementation.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=606005#comment-606005):_

An initial implementation for discussion and planning this schema is available in RAD PR-163: #163

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-72?focusedCommentId=625975#comment-625975):_

Closing this ticket as [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) does nto need the schema for his RDM implementation.
