### ISSUE TITLE
Define a schema for dithered observations

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#208]
_Issue [RAD-102](https://jira.stsci.edu/browse/RAD-102) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

For JWST the schema is in the core.schema.yaml file

<https://github.com/spacetelescope/jwst/blob/master/jwst/datamodels/schemas/core.schema.yaml#L1043>

 

Coordinate with RTB and PSS? <https://jira.stsci.edu/browse/RPSDB-499>

**Comment by PaulHuwe** [comment]
@ddavis-stsci Is this still being planned, or has it been supplanted by associations / mosaic / etc.?

**Comment by ddavis-stsci** [comment]
APT still supports gap dithers and sub-pixel dithers
https://innerspace.stsci.edu/display/RI/Roman+WFI+dither+patterns
So yes we should support that.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/RAD-102?focusedCommentId=972522#comment-972522):_

Linked RAD issue is closed.
