### ISSUE TITLE
Write a schema for IPC reference file

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#210]
_Issue [RAD-100](https://jira.stsci.edu/browse/RAD-100) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

RTB will deliver an IPC reference file to support the Roman simulator. There are no plans to have an IPC correction in the pipeline.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by ddavis-stsci** [comment]
Closing since Jira issue is resolved.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625103#comment-625103):_

This is implemented in RAD PR-203: #203

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=621610#comment-621610):_

This is just a single ndarray giving the IPC kernel.  One per detector is adequate; we don't expect this to depend on wavelength.  Tyler suggests including the p_optical_element attribute in the schema anyway in case we choose later on to introduce some wavelength dependence.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-100?focusedCommentId=625773#comment-625773):_

This PR was approved and merged.
