### ISSUE TITLE
Guidewindow start/stop

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#211]
_Issue [RAD-108](https://jira.stsci.edu/browse/RAD-108) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

The gw_window_xstart, gw_window_ystart, gw_window_xstop, gw_window_ystop need to be updated from float to integer to match what is delivered from the S/C.

These attributes should also be added to the guidestar-1.0.0.yaml attributes so that the guide window position can be carried in the science files without having to go and find the guidewindow files.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625460#comment-625460):_

This is implemented in RAD PR-205: #205

**Comment by ddavis-stsci** [comment]
closing since Jira issue is resolved.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625460#comment-625460):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625460#comment-625460):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625780#comment-625780):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625460#comment-625460):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625780#comment-625780):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625780#comment-625780):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625460#comment-625460):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625780#comment-625780):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625780#comment-625780):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625460#comment-625460):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625780#comment-625780):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625460#comment-625460):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-108?focusedCommentId=625780#comment-625780):_

PR approved and merged.
