### ISSUE TITLE
Update guide window attributes in the guidestar schema

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#212]
_Issue [RAD-103](https://jira.stsci.edu/browse/RAD-103) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

We need additional attributes in the "guidestar" schema for flagging the pixels in the raw file where the guide window is. These are "gw_window_xstart", "gw_window_ystart", "gw_window_xsize", "gw_window_ysize", all of type integer. 

SDF will populate these in the raw files using the respective values in the guide window file, after associating a raw file with the appropriate guide window file.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by ddavis-stsci** [comment]
The gw_window_* attributes added to the guidestar schema need to have the destination field included, e.g.
```
  gw_window_xstart:
    title: Guide window x start position on the detector
    type: integer
 
```
and add 
```
      archive_catalog:
      datatype: integer
      destination: [ScienceCommon.gs_window_xstart]
```
to the six gw_window fields.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625461#comment-625461):_

This is implemented in RAD PR-205: #205

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-103?focusedCommentId=625777#comment-625777):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630076#comment-630076):_

[David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) Looking at the code in <https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidewindow-1.0.0.yaml> it looks like this was completed. If so please close the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RAD-112?focusedCommentId=630088#comment-630088):_

We still need to add the archive destination in the 
<https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/guidestar-1.0.0.yaml>

It is correct in the guidewindow  schema referenced above.

We are still waiting for final input from the archive folks.
