### ISSUE TITLE
Create PR Template

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#217]
Create a template for PRs to encompass for following information:

Issue Number

Description

Checklist boxes:
Confirmation this was approved in RAD meeting
added entry in `CHANGES.rst` under the corresponding subsection

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633830#comment-633830):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-114](https://jira.stsci.edu/browse/RAD-114)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633830#comment-633830):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-114](https://jira.stsci.edu/browse/RAD-114)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633830#comment-633830):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-114](https://jira.stsci.edu/browse/RAD-114)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633830#comment-633830):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-114](https://jira.stsci.edu/browse/RAD-114)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-114](https://jira.stsci.edu/browse/RAD-114)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633830#comment-633830):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-114](https://jira.stsci.edu/browse/RAD-114)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633830#comment-633830):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-114](https://jira.stsci.edu/browse/RAD-114)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-114?focusedCommentId=633498#comment-633498):_

This is implemented in RAD PR-221: #221
