### ISSUE TITLE
Make Source Detection Optional

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#223]
The `source_detection` entry in the cal_step should be optional - it needs to be removed from the required list.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-116](https://jira.stsci.edu/browse/RAD-116)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635292#comment-635292):_

This is implemented in RAD PR-224: #224

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635383#comment-635383):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-116](https://jira.stsci.edu/browse/RAD-116)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635292#comment-635292):_

This is implemented in RAD PR-224: #224

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635383#comment-635383):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-116](https://jira.stsci.edu/browse/RAD-116)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635383#comment-635383):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-116](https://jira.stsci.edu/browse/RAD-116)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635292#comment-635292):_

This is implemented in RAD PR-224: #224

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635383#comment-635383):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-116](https://jira.stsci.edu/browse/RAD-116)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635292#comment-635292):_

This is implemented in RAD PR-224: #224

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-116](https://jira.stsci.edu/browse/RAD-116)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635292#comment-635292):_

This is implemented in RAD PR-224: #224

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635383#comment-635383):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635292#comment-635292):_

This is implemented in RAD PR-224: #224

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635383#comment-635383):_

PR approved and merged.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-116](https://jira.stsci.edu/browse/RAD-116)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635292#comment-635292):_

This is implemented in RAD PR-224: #224

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-116?focusedCommentId=635383#comment-635383):_

PR approved and merged.
