### ISSUE TITLE
Remove pixelarea schema from schemas

### ISSUE THREAD

**Issue by ddavis-stsci** [spacetelescope/rad#243]
Remove the rad/resources/schemas/pixelarea-1.0.0.yaml file.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-124](https://jira.stsci.edu/browse/RAD-124)._
