### ISSUE TITLE
Add schema for background

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/rad#247]
https://github.com/spacetelescope/romancal/pull/687 implements sky matching for `romancal`, and updates a (temporary) "background" dictionary in `ImageModel.meta`. The dict currently has three keys:
* `level` (`astropy.units.Quantity`)
* `subtracted` (`bool`)
* `method` (`str`)

`method` can have the options defined by the spec:
```
option('local', 'global', 'match', 'global+match', default='match')
```
This should be implemented with a schema in rad.

**Comment by ddavis-stsci** [comment]
changes merged.

**Comment by braingram** [comment]
I'm failing to find a background schema. @ddavis-stsci would you help me locate which schema defines this attribute?

**Comment by braingram** [comment]
Per a conversation with @schlafly at the moment background does not have a schema and it's uncertain if it will get one (since it's optional). I'll try to update this issue if I learn more.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-172](https://jira.stsci.edu/browse/RAD-172)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-172?focusedCommentId=711925#comment-711925):_

The schema is added in PR-432: #432

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-172?focusedCommentId=712202#comment-712202):_

PR approved and merged.
