### ISSUE TITLE
Update WFI Data Files

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#25]
Update WFI data files to utilize helper data objects (like variance, etc.)

**Comment by nden** [comment]
@PaulHuwe There's a PR linked. Can this be closed or is there more work to be done?

**Comment by PaulHuwe** [comment]
> @PaulHuwe There's a PR linked. Can this be closed or is there more work to be done?

I think that is a mis-link. This issue has not been addressed, to my knowledge.
