### ISSUE TITLE
Update program field from int to string

### ISSUE THREAD

**Issue by ddavis-stsci** [spacetelescope/rad#251]
In the associations the program is a string not an integer and the schema should reflect that. 
An example of the program in an association is "program": "00992",

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-119](https://jira.stsci.edu/browse/RAD-119)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-119?focusedCommentId=643349#comment-643349):_

#255

spacetelescope/roman_datamodels#175

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-119?focusedCommentId=643349#comment-643349):_

#255

spacetelescope/roman_datamodels#175

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-119](https://jira.stsci.edu/browse/RAD-119)._

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-119](https://jira.stsci.edu/browse/RAD-119)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-119?focusedCommentId=643349#comment-643349):_

#255

spacetelescope/roman_datamodels#175

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-119](https://jira.stsci.edu/browse/RAD-119)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-119?focusedCommentId=643349#comment-643349):_

#255

spacetelescope/roman_datamodels#175
