### ISSUE TITLE
Minor RAD - RDM Discrepancies

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#260]
Testing has highlighted some minor RAD discrepancies.

Should be an integer:
https://github.com/spacetelescope/rad/blob/ceededa17904002b6f8c5251f06d3e12d049dabd/src/rad/resources/schemas/exposure-1.0.0.yaml#L350

Should specify string:
https://github.com/spacetelescope/rad/blob/ceededa17904002b6f8c5251f06d3e12d049dabd/src/rad/resources/schemas/reference_files/dark-1.0.0.yaml#L15-L16

Should specify string:
https://github.com/spacetelescope/rad/blob/ceededa17904002b6f8c5251f06d3e12d049dabd/src/rad/resources/schemas/reference_files/distortion-1.0.0.yaml#L15-L16

Should be corrected:
https://github.com/spacetelescope/rad/blob/ceededa17904002b6f8c5251f06d3e12d049dabd/src/rad/resources/schemas/reference_files/ref_exposure_type-1.0.0.yaml#L13-L16

**Comment by ddavis-stsci** [comment]
I would add the update for gw_science_file_source in 
src/rad/resources/schemas/guidewindow-1.0.0.yaml:
            archive_catalog:
              datatype: nvarchar(120)
              destination: [ScienceCommon.gw_science_file_source] --> [GuideWindow.common.gw_science_file_source]
