### ISSUE TITLE
Add cal_step for sky match

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/rad#265]
The sky match step in https://github.com/spacetelescope/romancal/pull/687/ will update the following attribute:
```python
dm.meta.cal_step.skymatch = step_status
```
([source](https://github.com/spacetelescope/romancal/blob/11018d80fd916050ad6b37502a3b7973fe180cc6/romancal/skymatch/skymatch_step.py#L213)) where `step_status` can be "INCOMPLETE" or "COMPLETE". In [a comment](https://github.com/spacetelescope/romancal/pull/687/files/11018d80fd916050ad6b37502a3b7973fe180cc6#r1197208510), @PaulHuwe requested I create this issue with a request to add a sky match entry in `cal_step`.

**Comment by ddavis-stsci** [comment]
Closing this since the change has been merged.
