### ISSUE TITLE
expand length of origin

### ISSUE THREAD

**Issue by kdupriestsci** [spacetelescope/rad#266]
origin-1.0.0.yaml has enum: ["STSCI", "IPAC/SSC"] and  datatype: nvarchar(5).  The datatype field should be expanded to allow for the longer string (and perhaps a bit longer to allow for future changes).

**Comment by WilliamJamieson** [comment]
So it looks like we need at least 8 characters, do you think 15-20 will give us the future flexibility?

**Comment by kdupriestsci** [comment]
15 characters is probably good, unless you have some ideas as to what additional values might be.
