### ISSUE TITLE
fill in values for archive_meta

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#289]
_Issue [RAD-130](https://jira.stsci.edu/browse/RAD-130) was created on JIRA by [Kimberly DuPrie](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kduprie):_

A new archive_meta tag has been added to RAD.  Fill it in with what makes sense for DADS.  One suggestion is an enumerated list of filetypes that the keywords apply to.  For example, wfi_science_raw would have science_wfi_level1.  Not sure if this makes sense or not, we need to think about it some more.  If we did this would we need to make sure that the yaml file exactly matches the fileType name or can they be allowed to diverge?

**Comment by PaulHuwe** [comment]
@relaxing @kdupriestsci Should the values be numeric (1, 2, etc.) or strings (science_wfi_level1, image_wfi_level2, mosaic_wfi_level3)?

**Comment by kdupriestsci** [comment]
I don't think we've decided how to use this field yet (other than whether or not it exists), so a string is probably the safest since it's the most flexible.

**Comment by kdupriestsci** [comment]
I assume will fill it in at some point in the future, but I think it's fine to close this ticket and we can open a new one when we have a better idea of what to populate this field with.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Brett Graham](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bgraham) on [JIRA](https://jira.stsci.edu/browse/RAD-130?focusedCommentId=972521#comment-972521):_

Linked RAD issue is closed.
