### ISSUE TITLE
Add Slope and Error to Dark

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#318]
_Issue [RAD-136](https://jira.stsci.edu/browse/RAD-136) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

Add an array called "dark_slope" that is float32 and has Ndim = 2 with units of DN / second.
Change the "err" array to have Ndim = 2 (data type and units are fine as is) and renamed "dark_slope_err".

**Comment by schlafly** [comment]
Units have to be the same as dark slope, DN/s.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-136?focusedCommentId=666733#comment-666733):_

An addendum PR has been pushed as well: #324
