### ISSUE TITLE
Implement photom support

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#34]
Needs to be implemented once table styles are decided upon.

**Comment by PaulHuwe** [comment]
Depends on issue #24

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-20](https://jira.stsci.edu/browse/RAD-20)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-20?focusedCommentId=535090#comment-535090):_

This has been fully implemented, complete with newly required testing, PR comments addressed, PR approved and merged.
