### ISSUE TITLE
Review lengths of strings in metadata

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/rad#342]
We hit an issue where roman.meta.program.category had a typo where SURVEY -> SURVYEY.  This caused downstream problems because roman.meta.program.category is specified in the database as an nvarchar(6), and SURVYEY has 7 characters.  We should review the lengths of all of the strings and tend to make them longer than the absolute minimum to fit the one word we know about so far.

Maybe default to ~20 characters for strings where we don't know what to expect.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-147](https://jira.stsci.edu/browse/RAD-147)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-147?focusedCommentId=683375#comment-683375):_

[Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) I would think this was a good thing - it caught an error. 

Isn't it better in this case to enumerate the values? Or does this bring other problems?

**Comment by schlafly** [comment]
@nden , If the possible values are really known and likely to change only rarely, I think enum's are reasonable.  But in this case I feel like we just picked a string length that was the length of our default and never looked again?  But maybe someone actually knows the values and they are all fewer than 6 characters?

I'm happy to be aggressive about allowing only 'allowed' things when we know what's allowed, but I don't think we should box ourselves in when we don't know what the possibilities are.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-147?focusedCommentId=732629#comment-732629):_

This is supplanted by work in #448

Closing.
