### ISSUE TITLE
Update Product Table Names

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#357]
The database table targets need to be renamed throughout the RAD schemas:
For L1 & L2: WFIExposure
For L3: WFIMosaic

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Tim Bieniosek](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tbieniosek) on [JIRA](https://jira.stsci.edu/browse/RAD-146?focusedCommentId=685513#comment-685513):_

Need help merging.
