### ISSUE TITLE
Split cal_step into L2 & L3

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#363]
Split the cal_step schema into one for level 2 and one for level 3.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-149](https://jira.stsci.edu/browse/RAD-149)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-149?focusedCommentId=683381#comment-683381):_

Can you provide some more details as to what is the goal here? Split cal_step into two tags? Or do the split within the cal_step tag? Also what is the motivation? When split are the two tags (assuming two tags) going to be used in different ways?

**Comment by PaulHuwe** [comment]
Maybe the better question for this ticket is if `cal_step` should be in mosaic at all? Level 2 steps aren't relevant to a mosaic image (beyond the values of it for its constituents, which is stored in the muxed individual_image_meta keyword).

**Comment by schlafly** [comment]
For L2 files, the cal_step resample never makes sense and will always take on some default value.  The cal_steps outlier_detection and skymatch kind of make sense; they are applied to individual images and we should update them in their L2 image models when we do so.  But we'll never set them in images we ordinarily send out.  We should keep them in the L2 schema, though.

For L3 files, I think the only cal_steps that could make sense are outlier_detection, skymatch, and resample.  Resample must be complete if we have an L3 file, so it's a bit redundant but fine.  skymatch and outlier_detection conceptually make sense though we'd populate them by looping over the input ImageModels and making sure that those have the skymatch and outlier detection steps complete.

I think the options are:
1. leave them merged and accept that the L3 and L2 files reference some conceptually weird steps.
2. split them, removing resample from L2 and removing everything but outlier_detection, skymatch, and resample from L3.  Update L3 to populate outlier_detection and skymatch according to the individual image metadata.
3. split them, removing resample from L2 and everything but resample from L3.

I think my preference is for (2), but at rather low priority.

**Comment by schlafly** [comment]
Okay, let's go ahead and do (2), but only if we expect it to be a modest effort (<1 week).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-149?focusedCommentId=690747#comment-690747):_

This is implemented in RAD PR-397: #397
