### ISSUE TITLE
Add `statistics` field to TVAC and FPS schemas

### ISSUE THREAD

**Issue by fjaviersanchez** [spacetelescope/rad#412]
After some discussion with some folks at RTB we thought that it would be useful to have an additional field called `statistics` or `image_summary_statistics` containing some summary statistics about the image that could be meaningful at the time of querying. These values would be populated at conversion.

Here are a couple of implementation options:

1. Have just one field called `image_summary_statistics` and this would be a dictionary containing some key-value pairs. This field would need to be searchable but not indexed. The description for this field would be `Summary statistics for image data cube`.
2. Alternatively, have 4 fields: `mean_counts_per_sec`, `median_counts_per_sec`, `max_counts`, `min_counts`. The descriptions would be `Mean number of counts per second`; `Median number of counts per second`, `Maximum number of counts in the data cube`, `Minimum number of counts in the data cube`, respectively. The first 2 would be `Quantity` objects with units of `DN/s` and the last two `Quantity` objects with units of `DN`. All of these should be searchable, but none of them should be indexed.

Either option would work for us, happy to discuss further.

**Comment by PaulHuwe** [comment]
Option 2 was selected by the Team, and will be implemented.

**Comment by fjaviersanchez** [comment]
Thank you!

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-171](https://jira.stsci.edu/browse/RAD-171)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-171?focusedCommentId=698653#comment-698653):_

This is implemented in RAD PR-423: #423

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-171?focusedCommentId=699132#comment-699132):_

PR approved and merged.
