### ISSUE TITLE
Rename `ngroups` to `n_resultants` for the TVAC and FPS schemas.

### ISSUE THREAD

**Issue by fjaviersanchez** [spacetelescope/rad#413]
Folks at RTB pointed out that using `ngroups` as a keyword in the exposure metadata can lead to some confusion about the meaning of these as Roman's resultants aren't exactly equivalent to JWST's groups. 

We would like to suggest that, at least for FPS and TVAC data, the `ngroups` keyword gets renamed to `n_resultants` (or `nresultants` whatever is most consistent with `romancal`), if it's possible. This would alleviate potential confusions and help us to have keywords more consistent with the current documentation.

**Comment by schlafly** [comment]
We want to do this, but as part of a larger reorganization of the L2 metadata that's ongoing---as you know, there are a lot of keywords of questionable value beyond ngroups.  It might be worth talking about the time frame for that review in the context of freezing the TVAC / FPS schemas.

**Comment by fjaviersanchez** [comment]
That sounds good to me. Thanks @schlafly! Pinging also @tddesjardins.
