### ISSUE TITLE
Fix TVAC & RPS Archive Cat Destinations

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/rad#415]
With the splintering off of TVAC and FPS into their own schemas, the archive catalog destinations from both their original schemas and their new schemas need updating.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-170](https://jira.stsci.edu/browse/RAD-170)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-170?focusedCommentId=698753#comment-698753):_

This is implemented in RAD PR-424: #424

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-170?focusedCommentId=699131#comment-699131):_

PR approved and merged.
