### ISSUE TITLE
Drop `filename_l1a` and `filename_pnt5` from database for TVAC and FPS schemas

### ISSUE THREAD

**Issue by fjaviersanchez** [spacetelescope/rad#416]
We (RTB) have been told that in the example file that we provided following the `rad` TVAC schema, the fields `filename_l1a` and `filename_pnt5` were much longer than the number of characters allocated (allocated 80 characters and one of them was 649 characters long). We don't know how stable the length of these fields is, as versions and locations in disk on the GSFC side are happening often, and we think that this is a field that is not going to be useful for 99.99% of the potential users. So we would like to request to please keep these fields on the schema but drop them from the database, so the length limit is not enforced.

Thank you in advance!

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-169](https://jira.stsci.edu/browse/RAD-169)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-169?focusedCommentId=698542#comment-698542):_

This is implemented in RAD PR-421: #421

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-169?focusedCommentId=699130#comment-699130):_

PR approved and merged.
