### ISSUE TITLE
Drop `filepath_level_pnt5` from TVAC/FPS database schema

### ISSUE THREAD

**Issue by fjaviersanchez** [spacetelescope/rad#417]
This is related to #416. In the same spirit as the other two fields requested to drop there, we'd like to request the field `fiilepath_level_pnt5` also to be dropped from the database schema (so a character limit is not enforced).

Thank you in advance!

**Comment by schlafly** [comment]
Sorry, trying to consolidate this, the goal for the near term is:
- the 4 new image statistics fields
- remove filepath_level_pnt5, filename_l1a, filename_pnt5 from database, leaving them alone in the L1 files.
Yes?

**Comment by fjaviersanchez** [comment]
Yes, correct. Apologies for the multiple tickets

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-168?focusedCommentId=698545#comment-698545):_

This is implemented in RAD PR-422: #422

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-168?focusedCommentId=699128#comment-699128):_

PR approved and merged.
