### ISSUE TITLE
Update aperture names 

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/rad#426]
Presently the aperture names in RAD are an enum with allowed values like WFI_01_FULL.  This doesn't match the SIAF, where the names are WFI01_FULL.  At some point this _did_ match the SIAF, but the SIAF was updated to use the normal WFI detector names.  We should probably remain in sync with the SIAF.

https://github.com/spacetelescope/pysiaf/blob/main/pysiaf/prd_data/Roman/roman_siaf.xml#L13
https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/aperture-1.0.0.yaml#L15-L21

My suggestion would be to extend the enum to cover both the old and new names, and then to retire the old names in a ~year, just to avoid causing the files that are currently around to all start breaking.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-177](https://jira.stsci.edu/browse/RAD-177)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-177?focusedCommentId=746088#comment-746088):_

This is implemented in RAD PR-498:
#498
