### ISSUE TITLE
Add ref_file entry for reference pixel subtraction reference file

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/rad#431]
Somewhere around here
https://github.com/spacetelescope/rad/blob/60110dba69f21f13f1bd038847b5caffa398005a/src/rad/resources/schemas/ref_file-1.0.0.yaml#L42
we should add an entry for the reference pixel subtraction reference file, and update the reference pixel subtraction step to fill out that information.

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-176](https://jira.stsci.edu/browse/RAD-176)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-176?focusedCommentId=745546#comment-745546):_

PR approved and merged.
