### ISSUE TITLE
Add MA table reference file

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/rad#456]
Schema to follow pending some discussion in RTB. Something like:

```
ma_table = {id0: {'name': name, 'read_pattern': list_of_lists}, id1: ...}
```

Example:

```
ma_table = {1: {'name': 'HLWAS', 'read_pattern': [[1], [2, 3, 4], [5]]}, ...}
```

Motivation: define MA table read_patterns and any other info needed for Roman I-Sim and SDF (L0 -> L1 conversion) to avoid needing to scrape info from PRD XML file. Force any MA table dependent reference files to match MA table options defined in new ref file. Happy to discuss further at rcal tag-up.

**Comment by schlafly** [comment]
Did this get superseded or is it not planned?  IIRC we did have discussions about this?
