### ISSUE TITLE
APCORR and ABVEGAOFFSET optional nulls

### ISSUE THREAD

**Issue by wcschultz** [spacetelescope/rad#488]
In trying to use the new APCORR and ABVEGAOFFSET reference file schemas, I noticed that "null" is not a valid option for their values. We don't want to be forced to specify values when they might not make sense. For example, the ABVEGAOFFSET does not make sense for dark, grism, or prism exposures so we would like to set it to None. 

In addition to "numbers" and "arrays" it would be helpful if the values within these two reference files could also be "Null".

Affiliated with this JIRA ticket: https://jira.stsci.edu/browse/RCAL-905 .

**Comment by PaulHuwe** [comment]
@WilliamJamieson I think this would fit well with the reference file unit work as well. Would you take it?

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-189](https://jira.stsci.edu/browse/RAD-189)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-189?focusedCommentId=757822#comment-757822):_

This is implemented in RAD PR-516:

#516

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-189?focusedCommentId=758715#comment-758715):_

PR approved and merged.
