### ISSUE TITLE
ePSF Schema Update

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/rad#501]
Some quick changes to the ePSF reference files:
- For the psf array, the dimensionality should be 5 (currently it is 4)
- Change the description of the psf array to the following:
     - Postage stamps of ePSF models. The 5-dimensional array is ordered by (defocus, spectral_type , grid_index, y, x), where defocus and spectral_type are in the file metadata, grid_index is the index of the pixel_x and pixel_y positions in the file metadata, and y and x are the axes of the 2-D postage stamp ePSF.
- Change the effective_temperature field to spectral_type with the following:
    - title: Spectral Type
    - description: Spectral type(s) of the SEDs used to create the ePSF(s) with chromatic variations. See the Roman Documentation system (RDox) for more information on mapping spectral types to colors in the WFI filter system.
    - dtype: array
         - items:
              - dtype: string

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-187](https://jira.stsci.edu/browse/RAD-187)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-187?focusedCommentId=747324#comment-747324):_

This is implemented in RAD PR-507:
#507

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-187?focusedCommentId=756974#comment-756974):_

PR approved and merged.
