### ISSUE TITLE
Enable the JIRA/github bot in this project

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#52]
_Issue [RAD-3](https://jira.stsci.edu/browse/RAD-3) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=525389#comment-525389):_

Submitted ticket RITM0070037 to have the bot metadata fields added to RAD.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=527568#comment-527568):_

I've got most of my ducks in a row for this, I just need the workflow simplified before I can deploy the bot.

**Comment by eslavich** [comment]
(Testing comment from GitHub to Jira)

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Edward Slavich](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eslavich) on [JIRA](https://jira.stsci.edu/browse/RAD-3?focusedCommentId=532157#comment-532157):_

The bot is installed and seems to be running fine.
