### ISSUE TITLE
reference files should not require most of the information in basic-1.0.0

### ISSUE THREAD

**Issue by perrygreenfield** [spacetelescope/rad#54]
Most of the information in this schema is irrelevant for reference files, and can be very misleading. CRDS context, for example, should not be in the file since it may be used in several contexts. Likewise for calibration_software_version, crds_software_version, prd_software_version. Telescope is already required in another schema. If file date and such are needed, they should go in the ref_common schema and basic-1.0.0 removed from ref_common.

**Comment by nden** [comment]
@stscijgbot-rstdms

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-21](https://jira.stsci.edu/browse/RAD-21)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RAD-21?focusedCommentId=541492#comment-541492):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) - should this ticket be traceable back to other Roman work, or is that coming in the future.

**Comment by nden** [comment]
Resolved by #59

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RAD-21?focusedCommentId=541508#comment-541508):_

[Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) Linked to an epic now.
