### ISSUE TITLE
wfi_science_raw data arrays

### ISSUE THREAD

**Issue by nden** [spacetelescope/rad#55]
Roman will not have a `zeroframe` and `refout`. Remove them from `wfi_science_raw`.

**Comment by nden** [comment]
@stscijgbot-rstdms

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-22](https://jira.stsci.edu/browse/RAD-22)._

**Comment by PaulHuwe** [comment]
I have removed these during my DQ work. I will put in a PR for this soon.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-22?focusedCommentId=537232#comment-537232):_

This is implemented in #61

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-22?focusedCommentId=539161#comment-539161):_

PR Not yet approved.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-22?focusedCommentId=539355#comment-539355):_

This is blocked by (mistakenly) sharing the same PR as RAD-24, which is blocked by INS.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-22?focusedCommentId=539493#comment-539493):_

This is unblocked, and work is resuming.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-22?focusedCommentId=539931#comment-539931):_

This is back in PR with all requested changes made.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-22?focusedCommentId=540387#comment-540387):_

This PR has been merged.
