### ISSUE TITLE
Corrections to core schema

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/rad#82]
After discussing with @ddavis-stsci, @PaulHuwe, and Andrea Bellini today, we found some corrections to the core schema that should be implemented. These are mostly just clarifications to the metadata descriptions:

* exposure:
     * start_time, mid_time, end_time should be of data type "string"
* guidestar:
     * Add units to descriptions of gs_ra, gs_dec, etc. (should be decimal degrees)
     * Remove all references to FGS in descriptions.
* observation:
     * Add examples to descriptions of _number keys (e.g., program_number 'PPPPP')

**Comment by stscijgbot-rstdms** [comment]
_This issue is tracked on JIRA as [RAD-35](https://jira.stsci.edu/browse/RAD-35)._

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-35?focusedCommentId=551167#comment-551167):_

This will need a corresponding ticket for the Roman_Datamodels work these changes necessitate. I will post that ticket here once made.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-35?focusedCommentId=551210#comment-551210):_

I have implemented most of these changes, but am still researching a couple points before I put it in a PR.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-35?focusedCommentId=551316#comment-551316):_

This is implemented in PR RAD-91:
#91

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-35?focusedCommentId=551348#comment-551348):_

The related ticket for Roman_Datamodel test updates is here:
<https://jira.stsci.edu/browse/RCAL-222>

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-35?focusedCommentId=551955#comment-551955):_

Updated for more PR comments, wherein I also reviewed Roman-STScI-000193 and updated the metadata to those specifications.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-35?focusedCommentId=552306#comment-552306):_

Confirmed and merged.
