### ISSUE TITLE
Add Mode To Reference Schemas

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/rad#87]
_Issue [RAD-38](https://jira.stsci.edu/browse/RAD-38) was created on JIRA by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe):_

The following reference files are viewing mode dependent and thus require the exposure type as a CRDS selector.

The schemas (list from INS):

Dark

Readnoise

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-38?focusedCommentId=551154#comment-551154):_

This is in PR:
#90

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-38?focusedCommentId=551658#comment-551658):_

I refactored the code to address the comments, remove any concerns of unwanted database keywords in reference files, and allow for flexibility with reference exposure keywords. It is still in review.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-38?focusedCommentId=551659#comment-551659):_

The ticket for the associated RDM work is RCAL-225:
<https://jira.stsci.edu/browse/RCAL-225>

**Comment by nden** [comment]
What is the motivation for this change? Are these reference files going to be dependent on exposure type and so `meta.exposure.type` will be a CRDS selector? If so please make this clear in the ticket.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RAD-38?focusedCommentId=551698#comment-551698):_

I have updated the ticket, and will update RAD-39 as well.
