### ISSUE TITLE
leg_number definition missing from observation-1.0.0

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/rad#9]
The observation-1.0.0 schema lists `leg_number` as a required property, but it's missing from the `properties` list.

**Comment by ddavis-stsci** [comment]
Leg_number is now segment. See https://innerspace.stsci.edu/display/ROMAN/Filenaming+Discussion+on+2021-03-31

**Comment by eslavich** [comment]
Thanks, and it looks like this has since been fixed in main.
